### ISSUE TITLE
turn all ucanto packages into one plz ?

### ISSUE THREAD

**Issue by hugomrdias** [web3-storage/ucanto#157] opened 2022-12-02 12:24 UTC
its way easier to manage one package than several in all regards and avoids problems like the last publish that bumped several packages with a patch when those updated to a major breaking change version of `principal`

/cc @Gozala

**Comment by Gozala** [comment] 2022-12-10 22:22
duplicate of #161

**Closed by Gozala** 2022-12-10 22:22 UTC
